### ISSUE TITLE
BeamNG.gym needs to configure an environment variable. How can I configure it in Win10?

### ISSUE THREAD

**Issue by ncepu5** [BeamNG/BeamNG.gym#2]
BeamNG.gym needs to configure an environment variable. How can I configure it in Win10?

**Comment by aivora-beamng** [comment]
Hi,
there are multiple ways how to open the "Environment Variables" window.
![image](https://github.com/BeamNG/BeamNG.gym/assets/93574498/83919cd6-5711-437b-9690-fa0677c0789f)

Or you can press Win+R and run:
```
SystemPropertiesAdvanced
```
and click the "Environment Variables..." button.

Then you need to set up a variable called `BNG_HOME` which points to the directory where BeamNG.tech is installed:
<img width="782" alt="env" src="https://github.com/BeamNG/BeamNG.gym/assets/93574498/c7674a6b-9830-4249-a0df-806a8be697a2">
